### ISSUE TITLE
Game freezing on campaign map Carthago

### ISSUE THREAD

**Issue by dickulus** [bvschaik/julius#165]
On campaign map Carthago, the game randomly freezes and stops responding, only thing you can do is kill it.

To reproduce:
Load the attached save into Julius, set speed at 500% and let the game play for about 15-30 seconds of irl time. At some point the game freezes and stops responding. The bug happens sooner if you have more walkers on the map. My guess would be a memory corruption, because if you are lucky, right before the game freezes, you can see random walker sprites or whole walkers popping around the map randomly. This tends to happen only if you have a shitton of walkers (like a lot of new imigrant on a already crowded map).

Happens both on the latest stable and unstable version of Julius. The save was created with the stable version.

**Comment by dickulus** [comment]
[bug.zip](https://github.com/bvschaik/julius/files/3487355/bug.zip)

**Comment by bvschaik** [comment]
Thanks for reporting. Which operating system are you running?

I've been able to reproduce it using the Mac build, and it's an infinite loop caused by what indeed looks like a memory corruption with the walkers. I'll have to investigate where this occurs, these kind of issues are the hardest to debug so it might take a while 😟

**Comment by dickulus** [comment]
Windows 10

**Comment by dickulus** [comment]
it's also worth noting, that if i load this save into original Caesar III, the same thing happens. Perhaps the infamous walker limit?

**Comment by bvschaik** [comment]
No, it's the infamous "Carthago freeze" which also occurs in the original C3. See for example reports [here](http://caesar3.heavengames.com/cgi-bin/forums/display.cgi?action=ct&f=2,7264,125,all), [here](http://caesar3.heavengames.com/cgi-bin/forums/display.cgi?action=ct&f=10,455,2975,all), [here](http://caesar3.heavengames.com/cgi-bin/forums/display.cgi?action=ct&f=2,3044,2750,all).

I just found and fixed the problem for Julius: rarely, when a walker gets removed, the memory is not cleared properly, leaving some traces for the new walker that gets assigned the same ID. This will result in "linked lists" that do not contain the proper elements, and this will cause an infinite loop (freeze) in certain cases. The game is prone to such errors when walker IDs are reused, and since Carthago has lots of large invasions (using many walker slots), the mission is especially sensitive to lock-ups.

But that should be fixed now, could you give 1.1.0.31 unstable a go?

**Comment by dickulus** [comment]
Ok, unstable 1.1.0.31 seems working fine, I played for like an hour with no crash with this save

**Comment by dickulus** [comment]
Also, I want to report another bug, if you load the save and look on the islands in top right corner, the fishing wharfs are bugged, they are not pointing into the sea, but they were when I saved the game.

**Comment by bvschaik** [comment]
Thanks for verifying!

The fishing wharfs: did you save the game with stable 1.1.0? If so, that's an issue that's already been fixed in unstable (see commit bf1b7ecf9356f86de15d769dfcce47e050798641).

**Comment by dickulus** [comment]
Yes I did

**Comment by gdu-axelor** [comment]
Hello,

Still appears on 1.7.0. 
Example : 
[ProcureurFreeze.zip](https://github.com/user-attachments/files/17182488/ProcureurFreeze.zip)

**Comment by dubgeo** [comment]
Hello,

Issue still appears on 1.7.0
Example : 
[ProcureurFreeze.zip](https://github.com/user-attachments/files/17182502/ProcureurFreeze.zip)

**Comment by bvschaik** [comment]
@dubgeo Was this save created using Caesar 3 or Julius?

Julius only prevents the corrupted state, it doesn't fix it in existing saves, since it's hard to detect. In your save, a tower sentry has itself as the next item in a list, resulting in an infinite loop while iterating that list.
